### PR TITLE
Always send `Authorization` header when authentication is requested (fixes #169)

### LINKED ISSUE #169: Authentication only sent when the server explicitly requests it
I realize the following may be a strange case, but I thought I'd create an issue anyway. 

I'm using the Android app, and I just replaced Transmission's built-in authentication with authentication in my reverse proxy. The proxy does *not* reply with a `WWW-Authenticate` header, and if no credentials were passed in by an `Authorization` header, it'll redirect to a login page. 

Now, I looked through the code for libtremotesf, which uses `QNetworkAccessManager` and its `authenticationRequired` signal to get credentials set on requests, which obviously doesn't work in my use case. 

Is it reasonable for me to ask for credentials to be sent regardless? If need be, I'm willing to create a PR for this. Thanks for considering it! And thanks a bunch for the wonderful app!

### PR DESCRIPTION
**Pull request by otaconix**
See #169: I have a setup where I let a proxy do authentication, and it doesn't respond with a `401` status and `WWW-Authenticate` header, as it usually redirects to a login page, but it *does* process the `Authorization` header when it's in the request. This PR makes it possible to use such a setup.

Tiny bonus: the first request to pass through the `QNetworkAccessManager` won't have to be performed twice, since authentication happens immediately.

### CODE REVIEW

**Comment by otaconix** [comment]
PS: I'm a C++ and Qt noob, any suggestions are welcome!

File: requestrouter.cpp [hunk 1]
```diff
@@ -238,6 +236,9 @@ namespace libtremotesf::impl {
         if (!mSessionId.isEmpty()) {
             request.setRawHeader(sessionIdHeader, mSessionId);
         }
+        if (mConfiguration.authentication) {
+            request.setRawHeader(QByteArray("Authorization"), QByteArray(mBasicAuthHeaderValue));
```
Comment (equeim) [inline requestrouter.cpp]: Please make header name a constant, like sessionIdHeader.

File: requestrouter.cpp [hunk 2]
```diff
@@ -162,6 +156,10 @@ namespace libtremotesf::impl {
             }
             logDebug(" - Timeout: {}", mConfiguration.timeout);
             logDebug(" - HTTP Basic access authentication: {}", mConfiguration.authentication);
+            if (mConfiguration.authentication) {
+                auto base64Credentials = QString("%1:%2").arg(mConfiguration.username, mConfiguration.password).toUtf8().toBase64();
```
Comment (equeim) [inline requestrouter.cpp]: RFC 7617 says that Normalization Form C should used for Unicode credentials, you can use QString::normalized before calling toUtf8() for that (https://doc.qt.io/qt-6/qstring.html#normalized)

**Review by equeim — CHANGES_REQUESTED** [review]
Nice job, thanks!

File: requestrouter.cpp (hunk 1 above)
Comment (otaconix) [reply requestrouter.cpp]: Do you also want a constant for the `Basic ` authentication scheme prefix?

EDIT: I could at least do `QByteArrayLiteral("Basic ").append(...)` so we don't instantiate a new byte array (which gets immediately copied to append the credentials) for every request.

Comment (equeim) [reply requestrouter.cpp]: The only thing `QByteArrayLiteral` would do here is remove one extra allocation in `setConfiguration` when creating `QByteArray("Basic")`. New QByteArray will still be immediately created on heap when calling `append` (also this happens only when server configuration is loaded, not for every request). It's still nice, but I think it would be simpler to just lift the whole header value into constant, as `QStringLiteral("Basic %1:%2")`, and the initialize `mBasicAuthHeaderValue` from it.

BTW copying resulting `mBasicAuthHeaderValue` for each request is kinda cheap because `QByteArray` is copy-on-write i.e. non-modified copies share the same underlying buffer (deep copy would still happen somewhere down the line when Qt writes headers to socket).

Comment (otaconix) [reply requestrouter.cpp]: > [...]  I think it would be simpler to just lift the whole header value into constant, as QStringLiteral("Basic %1:%2"), and the initialize mBasicAuthHeaderValue from it.

I'm not sure how that should work though: the value of the header isn't `Basic ${username}:${password}`, it's `Basic ${base64(normalize(concat(username, ":", password)))}`. Perhaps you meant `"Basic %1"`?

Something like this?

```cpp
const auto authorizationHeaderValueFormat = QString("Basic %1");
// snip...
mAuthorizationHeaderValue = authorizationHeaderValueFormat.arg(base64Credentials).toUtf8();
```

I'd be happy to do something like that, if you prefer.

Comment (equeim) [reply requestrouter.cpp]: Opps, you are right. I think it looks good now.

**Review by equeim — APPROVED** [review]
